//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_BUDGET_TYPE
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string BUDGET_TYPE { get; set; }
        public string BUDGET_TYPE_CONVERT { get; set; }
    }
}
