//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_RADYO_PAZSIRK_PAZSIRK
    {
        public int ID { get; set; }
        public string RADYO_NAME { get; set; }
        public string RADYO_NAME_EDIT { get; set; }
        public string RADYO_NAME_CONVERT { get; set; }
    }
}
