//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_ACIKHAVA_TURU
    {
        public int ID { get; set; }
        public string ACIKHAVA_TURU { get; set; }
        public string ACIKHAVA_TURU_MASTER { get; set; }
    }
}
