//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_DIGITAL_KODLAMA
    {
        public int ID { get; set; }
        public string BIRIM { get; set; }
        public string ANA_BASLIK { get; set; }
        public string PAZARLAMA_SIRKETI { get; set; }
        public string MECRA_MEDPLAN { get; set; }
        public string PAZARLAMA_SIRKETI_DIGITAL { get; set; }
    }
}
