//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MECRA_KODLAMA
    {
        public int ID { get; set; }
        public string MECRA { get; set; }
        public string MECRA_KODU { get; set; }
        public string MECRA_KODU_CONVERT { get; set; }
    }
}
