//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDPLAN_DETAYLI_FATURA_DOKUMU
    {
        public int ID { get; set; }
        public string AJANS { get; set; }
        public string MECRA_TURU { get; set; }
        public string INTERNET_KATEGORI { get; set; }
        public string INTERNET_RAPOR_ANA { get; set; }
        public string INTERNET_RAPOR_ALT { get; set; }
        public string SPOT_TIPI { get; set; }
        public string MUSTERI_KODU { get; set; }
        public string MUSTERI_GRUBU { get; set; }
        public string MUSTERI_ADI { get; set; }
        public string URUN_KODU { get; set; }
        public string URUN_ADI { get; set; }
        public string KAMPANYA { get; set; }
        public string EKIP { get; set; }
        public string PLAN_KODU { get; set; }
        public string PAZARLAMA_SIRKETI { get; set; }
        public string PAZARLAMA_SIRKETI_2 { get; set; }
        public string YAYNI_GRUBU { get; set; }
        public string SEHIR { get; set; }
        public string MECRA_KODU { get; set; }
        public string DONEM { get; set; }
        public string AYLAR { get; set; }
        public Nullable<int> ADET { get; set; }
        public Nullable<int> SURE { get; set; }
        public Nullable<double> NET_TUTAR_DOLAR { get; set; }
        public Nullable<double> MUSTERI_BRUT_TUTAR { get; set; }
        public Nullable<double> NET_TUTAR_TL { get; set; }
        public Nullable<double> INTERNET_SATIS_STOPAJ { get; set; }
        public Nullable<double> INTERNET_SATIS_STAPAJ_DAHIL { get; set; }
        public Nullable<double> INTERNET_ALIS_STOPAJ { get; set; }
        public Nullable<double> INTERNET_ALIS_STOPAJ_DAHIL { get; set; }
        public Nullable<double> MUSTERIDEN_GELEN_IADE { get; set; }
        public Nullable<double> MUSTERIDEN_GELEN_STOPAJ { get; set; }
        public Nullable<double> GERCEKLESEN_TUTAR { get; set; }
        public Nullable<double> GERCEKLESEN_TOPLAM { get; set; }
        public Nullable<double> AHB_TUTAR { get; set; }
        public Nullable<double> MUSTERIDEN_IADEN_GELEN_AHB { get; set; }
        public Nullable<double> GERCEKLESEN_AHB_TUTARI { get; set; }
        public string MUSTERI_IADE_FATURA_NO { get; set; }
        public Nullable<System.DateTime> MUSTERI_IADE_FATURA_TARIH { get; set; }
        public Nullable<double> ONCEKI_YIL_MDV_ORANI { get; set; }
        public Nullable<double> ONCEKI_YIL_MDV_GERLIRI { get; set; }
        public Nullable<double> BU_YIL_MDV_ORANI { get; set; }
        public Nullable<double> BU_YIL_MDV_GELIRI { get; set; }
        public Nullable<double> MECRA_FATURA_TUTARI { get; set; }
        public Nullable<double> MECRA_FATURA_STOPAJ_TUTARI { get; set; }
        public string MECRA_FATURA_NO { get; set; }
        public string MECRA_FATURA_TARIHI { get; set; }
        public string MECRA_FATURA_PARA_BIRIM { get; set; }
        public Nullable<double> MECRA_FATURA_TUTAR_DOVIZ { get; set; }
        public Nullable<double> IADE_TUTAR { get; set; }
        public Nullable<double> IADE_SONRASI_MECRA_FATURA_TUTARI { get; set; }
        public Nullable<double> MECRA_FARK_FATURA_TUTAR { get; set; }
        public string MECRA_FARK_FATURA_NO { get; set; }
        public string MECRA_FARK_FATURA_TARIH { get; set; }
        public string MECRA_FARK_FATURA_PARA { get; set; }
        public Nullable<double> MECRA_FARK_FATURA_TUTARI_DOVIZ { get; set; }
        public Nullable<double> FARK_IADE_TUTARI { get; set; }
        public Nullable<double> FARK_IADE_SONRASI_FATURA_TUTARI { get; set; }
        public Nullable<double> IADELER_SONRASI_MECRA_FATURA_TOP { get; set; }
        public Nullable<double> SATIS_ALIS_FARK { get; set; }
        public Nullable<double> SATIS_ALIS_STOPAJ_FARK { get; set; }
        public Nullable<double> SATIS_ALIS_STOPAJ_FARK_TOP { get; set; }
        public Nullable<System.DateTime> MECRA_IADE_FATURA_TARIH { get; set; }
        public string MECRA_IADE_FATURA_NO { get; set; }
        public Nullable<System.DateTime> MECRA_FARK_IADE_FATURA_TARIHI { get; set; }
        public string MECRA_FARK_IADE_FATURA_NO { get; set; }
        public string ORJINAL_FATURA_NO_YAYIN { get; set; }
        public Nullable<double> ORJINAL_FATURA_TUTAR_YAYIN { get; set; }
        public string ORJINAL_FATURA_NO_FARK { get; set; }
        public Nullable<double> ORJINAL_FATURA_TUTAR_FARK { get; set; }
        public string ORJINAL_AVANS_FATURA_NO { get; set; }
        public Nullable<System.DateTime> ORJINAL_AVANS_FATURA_TARIH { get; set; }
        public Nullable<double> ORJINAL_AVANS_FATURA_TUTAR { get; set; }
        public string ORJINAL_FATURA_NO_AHB { get; set; }
        public Nullable<System.DateTime> ORJINAL_FATURA_TARIH_AHB { get; set; }
        public Nullable<double> ORJINAL_FATURA_TUTAR_AHB { get; set; }
        public Nullable<double> ORJINAL_FATURA_TUTAR_STOPAJ { get; set; }
        public string ORJINAL_FATURA_NO_FARK_AHB { get; set; }
        public Nullable<System.DateTime> ORJINAL_FATURA_TARIH_FARK_AHB { get; set; }
        public Nullable<double> ORJINAL_FATURA_TUTAR_FARK_AHB { get; set; }
        public Nullable<double> ORJINAL_AVANS_FATURA_NO_AHB { get; set; }
        public Nullable<System.DateTime> ORJINAL_AVANS_FATURA_TARIH_AHB { get; set; }
        public Nullable<double> ORJINAL_AVANS_FATURA_TUTAR_AHB { get; set; }
        public string ORJINAL_FATURA_MUSTERISI { get; set; }
        public Nullable<double> ORJINAL_FATURA_TUTAR_TOPLAM_YAYIN { get; set; }
        public Nullable<double> ORJINAL_FATURA_TUTAR_TOPLAM_AHB { get; set; }
        public Nullable<double> ORJINAL_FATURA_TUTAR_TOPLAM_YAYIN_STOPAJ { get; set; }
        public Nullable<double> ORJINAL_FATURA_TUTAR_TOPLAM { get; set; }
        public string TASLAK_FATURA_NO_YAYIN { get; set; }
        public Nullable<System.DateTime> TASLAK_FATURA_TARIH_YAYIN { get; set; }
        public string TASLAK_FATURA_NO_FARK_YAYIN { get; set; }
        public Nullable<System.DateTime> TASLAK_FATURA_TARIH_FARK_YAYIN { get; set; }
        public string TASLAK_AVANS_FATURA_NO_YAYIN { get; set; }
        public Nullable<System.DateTime> TASLAK_AVANS_FATURA_TARIH_YAYIN { get; set; }
        public Nullable<double> TASLAK_AVANS_FATURA_TUTAR { get; set; }
        public string TASLAK_FATURA_NO_AHB { get; set; }
        public Nullable<System.DateTime> TASLAK_FATURA_TARIH_AHB { get; set; }
        public string TASLAK_FATURA_NO_FARK_AHB { get; set; }
        public Nullable<System.DateTime> TASLAK_FATURA_TARIH_FARK_AHB { get; set; }
        public string TASLAK_AVANS_FATURA_NO_AHB { get; set; }
        public Nullable<System.DateTime> TASLAK_AVANS_FATURA_TARIH_AHB { get; set; }
        public Nullable<double> TASLAK_AVANS_FATURA_TUTAR_AHB { get; set; }
        public Nullable<double> AHB_ORANI { get; set; }
        public string ACIKLAMA { get; set; }
        public string ALIM_SEKLI { get; set; }
        public Nullable<int> YIL { get; set; }
        public Nullable<int> AY_NO { get; set; }
        public string RAPOR_ALIM_SEKLI { get; set; }
        public string MECRA_FATURA_KIME_KESILIYOR { get; set; }
        public string RAPOR_KATEGORISI { get; set; }
        public string CNTENT { get; set; }
        public string PO_NO { get; set; }
        public string ALT_PO_NO { get; set; }
        public Nullable<double> PO_TUTAR { get; set; }
        public string SATIS_FATURA_KAYNAK { get; set; }
        public string PLAN_SON_KAYIT_BILGISI { get; set; }
        public string PLAN_SON_KAYDEDEN_EPOSTA { get; set; }
        public string PLAN_SYMPHONY_ID { get; set; }
        public string SPOT_SYMPYONH_ID { get; set; }
        public string ENVANTER_KAPSAM { get; set; }
        public string MECRA_ADI { get; set; }
        public string IS_KOLU { get; set; }
        public Nullable<double> ORT_DOLAR_KURU { get; set; }
        public Nullable<System.DateTime> ORJINAL_FATURA_TARIH_YAYIN { get; set; }
        public Nullable<System.DateTime> ORJINAL_FATURA_TARIH_FARK { get; set; }
        public string PLAN_NOTLARI { get; set; }
    }
}
