//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DAS_CONVERTEntities : DbContext
    {
        public DAS_CONVERTEntities()
            : base("name=DAS_CONVERTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENT_KODLAMA> CLIENT_KODLAMA { get; set; }
        public virtual DbSet<DG_ALTBASLIK> DG_ALTBASLIK { get; set; }
        public virtual DbSet<DG_ANABASLIK_PROGRAMMATIC> DG_ANABASLIK_PROGRAMMATIC { get; set; }
        public virtual DbSet<DG_ANABASLIK_RESERVE> DG_ANABASLIK_RESERVE { get; set; }
        public virtual DbSet<DG_ANABASLIK_SEARCH> DG_ANABASLIK_SEARCH { get; set; }
        public virtual DbSet<DG_ANABASLIK_SOCIAL> DG_ANABASLIK_SOCIAL { get; set; }
        public virtual DbSet<DG_ANABASLIK_TECH_COST> DG_ANABASLIK_TECH_COST { get; set; }
        public virtual DbSet<DG_ANABASLIK_VAS> DG_ANABASLIK_VAS { get; set; }
        public virtual DbSet<DG_ANABASLIK_XAXIS> DG_ANABASLIK_XAXIS { get; set; }
        public virtual DbSet<DG_BIRIM> DG_BIRIM { get; set; }
        public virtual DbSet<MASTER_ACIKHAVA_TURU> MASTER_ACIKHAVA_TURU { get; set; }
        public virtual DbSet<MASTER_BUDGET_TYPE> MASTER_BUDGET_TYPE { get; set; }
        public virtual DbSet<MASTER_DIGITAL_KODLAMA> MASTER_DIGITAL_KODLAMA { get; set; }
        public virtual DbSet<MASTER_MECRA_TRADING_AJANS> MASTER_MECRA_TRADING_AJANS { get; set; }
        public virtual DbSet<MASTER_MEDIA_AGENCY> MASTER_MEDIA_AGENCY { get; set; }
        public virtual DbSet<MASTER_MEDIA_VEHICLE_TYPE> MASTER_MEDIA_VEHICLE_TYPE { get; set; }
        public virtual DbSet<MASTER_OUTDOOR_KODLAMA> MASTER_OUTDOOR_KODLAMA { get; set; }
        public virtual DbSet<MASTER_PURCHASE_TYPE> MASTER_PURCHASE_TYPE { get; set; }
        public virtual DbSet<MASTER_RADYO_PAZSIRK_MECRA> MASTER_RADYO_PAZSIRK_MECRA { get; set; }
        public virtual DbSet<MASTER_RADYO_PAZSIRK_PAZSIRK> MASTER_RADYO_PAZSIRK_PAZSIRK { get; set; }
        public virtual DbSet<MASTER_SEHIR> MASTER_SEHIR { get; set; }
        public virtual DbSet<MASTER_SPONSORSHIP> MASTER_SPONSORSHIP { get; set; }
        public virtual DbSet<MASTER_YEREL_KODLAMA> MASTER_YEREL_KODLAMA { get; set; }
        public virtual DbSet<MECRA_KODLAMA> MECRA_KODLAMA { get; set; }
        public virtual DbSet<PAZARLAMASIRKETI_KODLANMIS> PAZARLAMASIRKETI_KODLANMIS { get; set; }
        public virtual DbSet<ROL_LIST> ROL_LIST { get; set; }
        public virtual DbSet<USER_LIST> USER_LIST { get; set; }
        public virtual DbSet<MUSTERI_GRUPLARI> MUSTERI_GRUPLARI { get; set; }
        public virtual DbSet<MEDPLAN_DETAYLI_FATURA_DOKUMU> MEDPLAN_DETAYLI_FATURA_DOKUMU { get; set; }
        public virtual DbSet<DIGITAL_KODLAMA_GRUPLARI> DIGITAL_KODLAMA_GRUPLARI { get; set; }
    }
}
